Sprint 2
romatou/middle.messenger.praktikum.yandex pull request #3
Opened 2022-08-14 18:46 UTC by romatou

Здравствуйте!

Из последних сил доделал, что смог по заданию. Буду рад получить фидбэк. Были сложности с валидацией и и TypeScript. Отправляю в последние часы до дедлайна 😌

2022-08-15 08:39 UTC, podlovchenko requested changes
Привет) В целом все хорошо

Есть пара замечаний
1. Нет валидации на странице редактирования профиля
2. tsconfig составлен не по заданию
```
"noImplicitAny": true,

"noUnusedLocals": true,

"noUnusedParameters": true,

"sourceMap": true,

"strictNullChecks": true
```
должны быть в compilerOptions
3. Много ошибок при команде npm run lint

2022-08-15 08:39 UTC, podlovchenko commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^5.31.0",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-08-15 08:39 UTC, podlovchenko commented on src/components/button/Button.ts
> +  events?: object
Тип object не о чем не говорит, лучше описать отдельным типом какие поля могут быть

2022-08-15 08:39 UTC, podlovchenko commented on src/components/form/template.hbs
> +{{{button}}}
В проекте в некоторых файлах есть ошибка EOF
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-08-15 08:39 UTC, podlovchenko commented on src/components/input/Input.scss
> +    border: 1px solid #a0aec0;
Цвета лучше указывать через css переменные, так будет понятнее, что это за цвет при просмотре кода и проще редактировать цвета по всему проекту

2022-08-15 08:39 UTC, podlovchenko commented on src/components/link/Link.ts
> +export default class Link extends Block {
Почему тип Props не указывается для дженерика

2022-08-15 08:39 UTC, podlovchenko commented on src/components/link/Link.ts
> +  }
Конструктор можно не указывать, еси в нем только вызов родительского

2022-08-15 08:39 UTC, podlovchenko commented on src/core/HTTPTransport.ts
> +      xhr.open(method, !!data ? `${url}${queryStringify(data)}` : url)
Использование !! здесь излишне, data и так приводится к boolean в условии

2022-08-15 08:39 UTC, podlovchenko commented on src/pages/chats/dialog/Dialog.scss
> +    form {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-08-16 16:50 UTC, romatou commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^5.31.0",
Делал вручную, а он новые пакеты добавлял с ^. Оказалось надо добавить `.npmrc` и `save-exact=true`

2022-08-16 16:51 UTC, romatou commented on src/components/button/Button.ts
> +  events?: object
Поправил!

2022-08-16 16:51 UTC, romatou commented on src/components/form/template.hbs
> +{{{button}}}
Prettier удалял. Нужно было добавить в `.prettierrc` `overrides`

2022-08-16 16:52 UTC, romatou commented on src/components/input/Input.scss
> +    border: 1px solid #a0aec0;
Исправил

2022-08-16 16:52 UTC, romatou commented on src/components/link/Link.ts
> +export default class Link extends Block {
Новый компонент, который еще не использовал и случайно добавил в репозиторий

2022-08-16 16:54 UTC, romatou commented
Не знаю верно ли я отправил правки (через amend и force push) вместо нового коммита. Уточнял у наставника, он ничего важного про это не сказал.

2022-08-16 20:01 UTC, podlovchenko commented
Добрый вечер)

Для исправления замечаний лучше делать новый коммит, так ревьюер сможет просмотреть новые изменения, а не весь код проекта)

Сейчас есть ошибки типизации, можно посмотреть запустив команду `tsc --noEmit`,  было бы здорово их исправить

2022-08-17 06:19 UTC, merged