sprint_4
romatou/middle.messenger.praktikum.yandex pull request #6
Opened 2022-10-13 06:04 UTC by romatou

Приветствую. Направляю на проверку спринт 4.

2022-10-13 11:15 UTC, agadoev requested changes
Привет, @romatou , спасибо за работу
Основное, что я заметил - очень много any, object. По хорошему это вообще не нужно использовать и нужно будет уменьшить количество any в коде. Основная задача TS - предупреждать разработчика о возможной ошибки на этапе написания кода. Если везде использовать any, то польза TS'a аннулируется. Старайся типизировать все, что есть в твоем коде, тогда код будет надежнее и его легче будет поддерживать.
Так же я оставил несколько комментариев о том, как можно улучшить код. Поправь их, пожалуйста, и двинемся дальше :)

2022-10-13 11:15 UTC, agadoev commented on src/api/AuthAPI.ts
>    }
Тут тонкий момент с внедрением зависимостей в классы. Когда класс зависит от глобальной переменной напрямую (а xhr сейчас находится в глобальном скоупе), нарушается инкапсуляция класса. Это будет работать, но с точки зрения проектирования классов - это неправильно. Правильнее будет объявить приватное свойство класса, задать ему тип HTTPTransport и создать инстанс для этого поля в конструкторе. Тогда класс будет сам контролировать создание объекта, от которого он зависит

2022-10-13 11:15 UTC, agadoev commented on src/components/form/Form.ts
> +    const inputs: any = this.element?.querySelectorAll('input')
Тут не any, а NodeListOf<HTMLInputElement>
Можно написать так
```suggestion
    const inputs: any = this.element?.querySelectorAll<HTMLInputElement>('input')
```

2022-10-13 11:15 UTC, agadoev commented on src/components/link/Link.test.ts
> +  it('Должен рендериться', () => {
лучше все таки использовать латиницу

2022-10-13 11:15 UTC, agadoev commented on src/controllers/AuthController.ts
> +          if (res.status === 200) {
для того, чтобы получить зарезолвленное значение промиса асинхронной функции, нужно использовать либо await, либо .then, но не вместе

2022-10-13 11:15 UTC, agadoev commented on src/controllers/AuthController.ts
>            ChatController.requestChats()
Этот метод асинхронный, должен вызываться через await. Лучше вызывать все через await, так будет проще

2022-10-13 11:15 UTC, agadoev commented on src/modules/EventBus.ts
> +  private listeners: any
Надо прописать тип для listeners

2022-10-13 11:15 UTC, agadoev commented on src/pages/chats/dialog/Dialog.ts
>    messages: object
по названию свойства можно предположить, что тут будет массив, тогда почему бы не указать это в типе? На самом деле использование object не сильно отличается от any, потому что все есть объект

2022-10-13 11:15 UTC, agadoev commented on src/pages/profile/Profile.ts
>    }
Очень много any, нужно задать типы

2022-10-13 11:15 UTC, agadoev commented on src/pages/register/index.ts
> +        AuthController.create(queryData as RegisterFormModel)
Надо вызывать через await

2022-10-13 11:15 UTC, agadoev commented on src/utils/validate.ts
>        if (inputCount && inputCount < 3) {
Этот участок кода имеет очень высокую [цикломатическую сложность](https://learn.microsoft.com/ru-ru/visualstudio/code-quality/code-metrics-cyclomatic-complexity?view=vs-2022). Попробуй провести такой рефакторинг, который позволит снизить вложенность if-конструкций

2022-10-13 11:15 UTC, agadoev commented on webpack.config.js
> +
Хорошей практикой является разбиение вебпак конфига на два - для прода и для дева. В прод конфиге применяются различные оптимизации (чтобы уменьшить объем бандла и чтобы пользователь быстрее его загрузил), а в дев конфиге их нет (в процессе разработки мы часто перебилдим проект и лучше, чтобы это проходило быстрее). Попробуй разбить этот конфиг на два. Про оптимизации можно почитать на офф сайте вебпака

2022-10-14 20:00 UTC, romatou commented on package.json
> +    "test": "mocha --require ts-node/register --require ./.mocha.config.js ./src/**/*.test.ts"
Скрипт добавил

2022-10-14 20:00 UTC, romatou commented on src/api/AuthAPI.ts
>    }
Ошибку понял, скорректировал

2022-10-14 20:01 UTC, romatou commented on src/components/link/Link.test.ts
> +  it('Должен рендериться', () => {
Поменял

2022-10-14 20:01 UTC, romatou commented on src/controllers/AuthController.ts
>            ChatController.requestChats()
Поправил

2022-10-14 20:01 UTC, romatou commented on src/modules/EventBus.ts
> +  private listeners: any
Задал

2022-10-14 20:01 UTC, romatou commented on src/utils/validate.ts
>        if (inputCount && inputCount < 3) {
Переделал

2022-10-14 20:02 UTC, romatou commented
По возможности поправил максимально! Убрал все any, но где остались, то не понимаю как поправить пока, так как ломается все и боюсь не успеть. Обещаю поправить 🙏

2022-10-15 05:28 UTC, agadoev approved these changes
Привет, @romatou 
Спасибо за правки
Ничего страшного, что не получилось убрать все any. Главное, что сократил их количество. Это правда важно, ведь если писать везде any, то зачем вообще TS? В общем я вижу, что все поправлено, поэтому работа принимается :)

2022-10-15 05:31 UTC, romatou commented
@agadoev, спасибо большое. Очень этому рад и желаю хорошего дня

2022-10-15 11:42 UTC, merged